version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:7.4.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
volumes:
  my-db: